#!/bin/sh

cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Run OF utilities
rm -rf log.blockMesh
rm -rf log.icoFoam
rm -rf log.decomposePar
rm -rf log.reconstructPar
rm -rf processor*

runApplication blockMesh
runApplication decomposePar
runParallel $(getApplication)
runApplication reconstructPar

runApplication postProcess -func vorticity






